Percentatge de control de presència
ctrl-alt-d/django-aula pull request #133
Opened 2020-11-12 17:32 UTC by juaky

### Per diferents motius, qualsevol professor/a es pot deixar alguna classe sense controlar la presència.

- Per intentar recordar-li, s'afegeix un link a la pantalla del calendari setmanal on s'indica el percentatge de controls realitzats:

![image](https://user-images.githubusercontent.com/4690871/98973991-aef81680-2514-11eb-980b-b3cc76f7956c.png)

- L'enllaç li porta a un llistat de les classes on  no s'ha realitzat el control per tal de realitzar-lo:

![image](https://user-images.githubusercontent.com/4690871/98974562-55dcb280-2515-11eb-85c1-e8db7d3e40e2.png)

2020-11-12 20:12 UTC, ctrl-alt-d requested changes
Hola @juaky, sé que encara no m'has demanat revisió, però he posat uns comentaris perquè els miris quan tinguis una estona.

Merci!!!!

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/apps/presencia/views.py
> +    imparticions = Impartir.objects.filter(qProfessor & qFinsAra & qTeGrup)
Crec que aquí t'estàs deixant les imparticions que fas com a professor de guàrdia:

```python
qProfessor = Q(horari__professor=professor) | Q(professor_guardia=professor) 
```

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/menu.py
> +                      ("Estadístiques", 'varis__estadistiques__estadistiques', tots, None, None),
Ull!!! `tots` inclou famílies, crec que seria:

```python
("Estadístiques", 'varis__estadistiques__estadistiques', pr, None, None),
```

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/views.py
> +def estadistiques(request):
Ull, s'ha de limitar a professors:

```python
@login_required
@group_required(['professors'])
def estadistiques(request):
```

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/views.py
> +        qProfessor = Q(horari__professor=professor)
Aquí passa el mateix, falten les de guàrdia.

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/views.py
> +        nImparticionsLlistaPendent = imparticions.filter(professor_passa_llista__isnull=True).count()
Sé que aquest codi està copiat del que vaig fer jo a l'about, ara veig cosetes que potser pots arreglar a totes dues bandes si ets tan amable:

* Podries fer `nImparticios = nImparticionsLlistaPassada + nImparticionsLlistaPendent` per evitar una query a la base de dades.
* Crec que et falta un `distinct` per evitar possibles duplicats que es generin als joins:
```python
nImparticionsLlistaPassada = (
    imparticions
    .filter(professor_passa_llista__isnull=False)
    .order_by()
    .distinct()
    .count() )
```

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/views.py
> +        camp.contingut = u'{0}. {1}'.format(estadistica1, estadistica2)
Això no surt a la foto de l'exemple de la PR, és correcte?

2020-11-12 20:12 UTC, ctrl-alt-d commented on aula/utils/views.py
> +        )
Podries reemplaçar per aquest codi, sisplau?

```python
        nProfessor = Impartir.objects.filter(horari__professor=professor, horari__grup__isnull=False).count()
        nTotal = Impartir.objects.filter(horari__grup__isnull=False).count()
        estadistica2 = f'''Aquest curs impartirem {nTotal;,} hores de classe, d'aquestes, {nProfessor:,} les imparteixes tu.''
```

:raised_hands:

2020-11-24 10:43 UTC, juaky commented on aula/apps/presencia/views.py
> +    imparticions = Impartir.objects.filter(qProfessor & qFinsAra & qTeGrup)
S'ha modificat per tal que digui "de les teves classes" i així no s'inclouran les de guàrdia que no se sap quines són al llarg del curs.

2020-11-24 10:43 UTC, juaky commented on aula/utils/menu.py
> +                      ("Estadístiques", 'varis__estadistiques__estadistiques', tots, None, None),
Fet

2020-11-24 10:43 UTC, juaky commented on aula/utils/views.py
> +def estadistiques(request):
Fet

2020-11-24 10:43 UTC, juaky commented on aula/utils/views.py
> +        qProfessor = Q(horari__professor=professor)
S'ha modificat per tal que digui "Percentatge de passar llista a les teves imparticions:" i així no s'inclouran les de guàrdia que no se sap quines són al llarg del curs.

2020-11-24 10:43 UTC, juaky commented on aula/utils/views.py
> +        nImparticionsLlistaPendent = imparticions.filter(professor_passa_llista__isnull=True).count()
Fet

2020-11-24 10:45 UTC, juaky commented on aula/utils/views.py
> +        camp.contingut = u'{0}. {1}'.format(estadistica1, estadistica2)
Quedava amagat a la foto. Aquí ja es veu:
![image](https://user-images.githubusercontent.com/4690871/100083999-7fb5a380-2e4a-11eb-9753-859aff497e9a.png)

2020-11-24 10:45 UTC, juaky commented on aula/utils/views.py
> +        )
Fet

2020-11-26 14:09 UTC, juaky commented on aula/utils/views.py
> +def estadistiques(request):
Fet!

2020-12-18 14:25 UTC, merged