Comunicats
ctrl-alt-d/django-aula pull request #178
Opened 2021-12-15 18:51 UTC by amorilla

Les famílies podran comunicar les absències dels alumnes directament amb el Djau, el missatge serà rebut pel professorat afectat i pel tutor/a. Es poden fer comunicats amb antelació màxima d'una setmana.
En passar llista es veurà un botó si s'ha fet un comunicat.
![comun1](https://user-images.githubusercontent.com/48752002/146246150-3494831a-70e4-496f-afed-4cd927e54090.jpg)

Al justificador de tutoria també es mostrarà el comunicat en deixar el punter del ratolí damunt de la casella.
![comun2](https://user-images.githubusercontent.com/48752002/146246166-07d26e76-8fb0-4d1f-af94-862dd5ccd8d3.jpg)

Altres canvis:
Visualitza la foto de l'alumne al passar llista.
Des del justificador es pot fer recerca teclejant nom de l'alumne.
Alguna correcció per últimes versions de python
Corregit algun error.
Per activar l'opció s'ha d'afegir a settings_local.py:
CUSTOM_FAMILIA_POT_COMUNICATS = True

Fa falta fer migrate i collectstatic.
source venv/bin/activate
python manage.py migrate
python manage.py collectstatic
deactivate

2021-12-15 21:36 UTC, ctrl-alt-d requested changes
Hola Toni, genials les millores. He fet una anotació, un cop corregida, per la meva part, ja es pot fer merge.

2021-12-15 21:36 UTC, ctrl-alt-d commented on aula/apps/relacioFamilies/views.py
> +@login_required
Crec que aquí falten restriccions, una família que faci login podria obtenir informació que no li pertoca cridant aquest endpoint amb diferents id's d'alumnes. Caldria restringir-ho.

2021-12-17 10:49 UTC, amorilla commented
Corregit.

2021-12-21 09:00 UTC, juaky approved these changes
Hola Morilla,
Em sembla una aportació genial!

2021-12-21 09:06 UTC, ctrl-alt-d approved these changes

2021-12-27 11:59 UTC, merged

2022-01-05 10:08 UTC, juaky commented
Hola de nou @amorilla 
Tras fer aquest PR al meu entorn de proves sembla que els widgets han deixat de funcionar.
Per exemple aquest desplegable de reserva de material i el calendari també:

![image](https://user-images.githubusercontent.com/4690871/148199464-0fbcc028-bd2f-4967-8799-6aa02256934d.png)

Gràcies!!

2022-01-05 13:20 UTC, amorilla commented
Hola,
  Sembla un problema amb la versió de jquery, select2 o django-select2.
  Assegura't de tenir la versió correcte de jquery i select2 segons el master (aula/site-css/jquery  aula/site-css/select2)
  Haurien de fallar també els altres desplegables de tipus select2.
  Recomano:
```
git pull
source venv/bin/activate
pip install -r requirements.txt --upgrade
python manage.py collectstatic
python manage.py migrate
deactivate
```
Salutacions.

2022-01-10 08:01 UTC, juaky commented
Hola!
El problema era que tenia un fitxer base.html personalitzat dins la carpeta customising/templates i per tant agafava aquest. Ha estat modificar-lo i ja està.
Gràcies